### ISSUE TITLE
Communication between Participants and Bürokratt

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#11]
AS Bürokratt
I WANT TO communicate with Participants and vice versa on a machine-to-machine level
SO THAT as many actions as possible could be automated and covered with technical functionalities and responses

### Acceptance Criteria

> In the long run, Participants can not communicate with other Participants directly, but they do it within the scope of this project

> All communication will be mediated via **DMR** _(Distributed Message Room) - out of scope of this issue_

- [ ] Messages sent and received must be based on #78 
- [ ] Messaging functionalities can be used by Bürokratt
- [ ] Messaging functionalities can be used by Participants
- [ ] The scope of this issue is to communicate via REST calls

#### Functionalities

> By `participants` we mean any of the participants, including Bürokratt, its clients (Institutions and actual Participants), End Clients, etc.

> By `Participants` we mean contracted Participants, all of them related to Institutions

##### Generic functionalities applying to both Bürokratt and Participants

- [ ] #109
- [x] #111
- [ ] #112
- [ ] #113

##### Messages from Bürokratt to Participants

- [ ] ...

##### Messages from Participants to Bürokratt

- [ ] ...
