### ISSUE TITLE
Storing an accepted CentOps message sent by one participant to another

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#112]
AS AN Architect
I WANT approved CentOps messages to be saved on every Participant's local instance
SO THAT these could be used as information and/or triggers for further actions

### Acceptance Criteria

- [ ] Use #111 template as a validation for acceptance
- [ ] Store the message in a decrypted format by using #115 based on the encryption method defined in the manifest
- [ ] Store accepted CentOps messages inside an appropriate CentOps database table called `accepted_messages`
- [ ] Store message `metadata` of #78 as part of the message within `accepted_messages`

_**NOTES**_

_Possible message types when storing them are_

- `sent`
- `accepted`
- `received`
- `replied`
