### ISSUE TITLE
Bürokratt processes Participants' requests to start using Bürokratt

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#14]
AS A Bürokratt Project manager
I WANT TO process Participants' requests to start using Bürokratt
SO THAT I would have that process automated and easy as much as possbile

#### General requirements

- [ ] List all REST endpoints created and used to fulfill the AC of this issue as valid OpenAPI specs
- [ ] User-provided input must be validated against pre-approved options defined in an appropriate Ruuter DSL

#### Endpoints

- [ ] #72 to process Participants' request to start using Bürokratt

#### Business requirements

- [ ] Only users with appropriate permissions have access to process Participants' requests by re-using the template of #23 
- [ ] GUI is used to process Participants' requests

#### Expected functionalities

> All of the functionalities below are based on Postgres' database table

- [ ] List all requests to start using Bürokratt
- [ ] Update the state of the application according to https://github.com/buerokratt/Buerokratt-Architectural-Decision-Records/issues/32
- [ ] Update the content of the Participant's information
- [ ] Mark request as deleted

#### DSL

- [ ] Use `institutions` database table based on #24

#### GUI

- [ ] Follows the principles of https://github.com/e-gov/cvi and https://e-gov.github.io/cvi/?path=/story/intro--page
- [ ] Uses https://github.com/buerokratt/cvi as technical stack _(PS! Currently in progress to get React-based components there)_
- [ ] Input for GUI fields are fetched from an appropriate configuration file

**Comment by turnerrainer** [comment]
@turnerrainer will list the expected endpoints

**Comment by 1AhmedYasser** [comment]
Waiting 

- #25
