### ISSUE TITLE
Administrative tool to manage existing Participants

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#16]
AS A Bürokratt Product Manager
I WANT TO to have an administrative tool to manage existing Participants
SO THAT I could do it by using an appropriate GUI

#### General requirements

- [ ] List all REST endpoints created and used to fulfill the AC of this issue as valid OpenAPI specs
- [ ] User-provided input must be validated against pre-approved options defined in an appropriate Ruuter DSL

#### Expected functionalities

- [ ] List all Participants
- [ ] Update the state of the Participants
- [ ] Update any of the Participant's information
- [ ] Mark the Participants as deleted

#### GUI

- [ ] GUI for Product Manager to work with
- [ ] Based on #19
