### ISSUE TITLE
Communication with participants

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#2]
AS Bürokratt
I WANT TO notify Participants about available software updates
SO THAT they could initiate appropriate processes without any human interaction

AS A Participant
I WANT TO notify Bürokratt about planned outages
SO THAT the rest of the Bürokratt network could take this information into account

### Acceptance Criteria

- [ ] Bürokratt can send API-based messages to Participants
- [ ] Participants can send API-based messages to Bürokratt
- [ ] No third party can send API-based messages to Bürokratt
- [ ] No third party can send API-based messages to Participants
