### ISSUE TITLE
Create a `unique invitation ID` for Participants-to-be to be able to make requests to start using Bürokratt

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#22]
AS A Bürokratt Product Owner
I WANT only Participants-to-be pre-approved by Bürokratt Core Team to be able to send requests to start using Bürokratt
SO THAT these applications couldn't be used for bad intentions

### Acceptance Criteria

- [x] The service is accessible only for Bürokratt Core Team members with `Admin` permissions, see #23 for more
- [ ] GUI is used to add an email to which a new invitation ID will be linked with
- [ ] Every invitation must be matched with an Institution
- [x] `Unique invitation ID` as part of Postgres schema
- [ ] Request ID and email are linked
- [ ] Request ID can only be used once for account activation
- [x] Same email can be used for multiple invitation IDs
- [x] Valid `unique invitation ID` is shown on the screen after being processed
- [x] Valid invitation link / URL with `unique invitation ID` is shown on the screen after being processed

#### DSL

- [ ] After the request has been processed, an email is sent to the email provided via #32

#### GUI

- [ ] A simple GUI to add an email based on #19 
- [ ] Matching invitations with Institution is done by using a drop-down selection
- [ ] Submit button to save the request

**Comment by turnerrainer** [comment]
Moved to "In Progress" as using mock Ruuter DSL to mimic sending emails was added as an AC.
