### ISSUE TITLE
CentOps Admin user permissions

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#23]
AS AN Architect
I WANT all user permissions related to CentOps Admin to be documented
SO THAT they could be used as a single source of truth throughout all the related developments

#### General requirements

- [ ] User permissions stored based on https://github.com/buerokratt/Buerokratt-Architectural-Decision-Records/issues/33
- [ ] General requirements of https://github.com/buerokratt/Buerokratt-onboarding apply

##### Admin

- [ ] Template name `permissions/admin`
- [ ] Access only for users with `ROLE_ADMINISTRATOR` permissions

### Examples

- [ ] [Example TIM response for valid user JWT](https://github.com/buerokratt/Ruuter/blob/main/samples/tim/mock-response.yml)
