### ISSUE TITLE
Store Bürokratt Participants and their invitations in a database

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#24]
AS A DevOps
I WANT Bürokratt Institutions to be stored in a database
SO THAT I shouldn't do it manually

#### General requirements

- [ ] Liquibase pipeline is used to set up the initial database table
- [ ] Liquibase pipeline is used to adopt changes to the table
- [ ] _Ruuter -> Resql -> Postgres -> Resql -> Ruuter_ as a flow for communication
- [ ] Use denormalized database tables (`update` and `delete` are forbidden)
- [ ] Schemas for database tables will be provided and revisioned via pull requests case-by-case

#### General requirements for schemas

Every table has to have at least the following columns

- [ ] `ID` auto-incremented
- [ ] [Unique ID](https://en.wikipedia.org/wiki/Universally_unique_identifier) `UUID`
- [ ] `timestamp` to mark the current timestamp of the entry provided by Postgres

#### Database tables used

- [ ] ~`institutions_invitations`~ `participants_invitations` to store invitations sent to potential Institutions-to-be
- [ ] ~`institutions`~ `participants` to store both unprocessed and confirmed applications
- [ ] `institutions` to store Institutions added and further processed directly by Bürokratt Admins

**Comment by turnerrainer** [comment]
A prerequisite for https://github.com/buerokratt/CentOps/issues/22
