### ISSUE TITLE
Tool for Bürokratt Core Team to provide information about future updates

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#25]
AS Bürokratt Service Manager
I WANT TO create and provide technical manifests about Bürokratt's future updates
SO THAT Bürokratt Institutions could use them as triggers to launch their internal Bürokratt update scripts

### Acceptance Criteria

- [ ] Protocol for CentOps technical update manifest

#### General requirements

- [ ] In addition to a technical manifest, a free-form description of a planned update can be provided
- [ ] Manifests ara stored in a database table

#### Permissions

- [ ] Create new manifests
- [ ] Update existing manifests
- [ ] Delete existing manifests

> Sending the manifest will be mimicked as a REST API, will be later replaced with DMR

- [ ] Send manifests to the members of the Bürokratt Network

#### Restrictions

- [ ] Ruuter DSLs in `Ruuter.private`
- [ ] Restricted access for users with `administrator` and `devops` permissions only by using https://github.com/buerokratt/Ruuter/issues/159
- [ ] GUI in `GUI.private`

#### Functionality

> The following functionalities must have a REST endpoint

- [ ] Create a new manifest
- [ ] Update the contents of an existing manifest
- [ ] Change the status of an existing manifest
- [ ] Delete a manifest
- [ ] Fetch a list of all approved future update manifests
- [ ] Fetch content of a manifest based on a specified ID
- [ ] Post a message about the next update manifest to a specified endpoint _(DMR)_

#### GUI

- [ ] Provide `CRUD` operations for the manifest
- [ ] GUI to provide a list of approved future updates

**Comment by 1AhmedYasser** [comment]
@turnerrainer 

Here is my suggested structure for the manifest

```
{
    "version": "1.0",
    "buerokratt_version": "1.0",
    "created_at": "2023-06-01 09:50:23",
    "updated_at": "2023-06-03 05:20:51",
    "components": {
        "ruuter": "1.0",
        "resql": "1.0",
        "tim": "1.0",
        "data_mapper": "1.0",
        "database": "1.0",
        "users_db": "1.0",
        "services_db": "1.0",
        "centops_db": "1.0"
    },
    "extra_configs": {
        "automatic_updates": false
    },
    "security_configs": {
        "encryption_method": "aes",
        "decryption_method": "aes",
        "key": "customKey"
    }
}
```

- **Version**: The manifest structure version, incase it will be updated later
- **Buerokratt Version**: Burokratt system version
- **Created At**: Date & time of creating this manifest
- **Updated At**: Date & time of updating this manifest
- **Components**: Burokratt Stack components versions
- **Extra Configurations**: For any additional configs added to the manifest

Would you like this to be built on the database or folder structure or both ?
