### ISSUE TITLE
Remote updates

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#3]
AS A Bürokratt DevOps Engineer
I WANT all Participants to have an automated process to update Bürokratt-related software
SO THAT I shouldn't do it manually

AS A Bürokratt Client
I WANT TO have my instance of Bürokratt to be automatically updated software-wise
SO THAT I shouldn't plan any additional resources for it

### Acceptance Criteria

- [ ] Pre-installation test script to verify the correspondence of the environment
- [ ] Pre-installation script to install all necessary prerequisites to install Bürokratt
- [ ] Only software verified by Bürokratt can be installed
