### ISSUE TITLE
Reference documentation for CentOps Admin endpoints

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#33]
AS A Developer creating OpenAPI specs
I WANT TO have reference documentation for creating OpenAPI specs for CentOps Admin
SO THAT I would have all the necessary input for doing my job

#### General requirements

- [ ] Separate OpenAPI specs for mock services
- [ ] Separate OpenAPI specs for prod services
- [ ] Separate OpenAPI specs for private (admin) services
- [ ] Separate OpenAPI specs for public services

#### Required references

> The following sources must be covered fully, even if not all of them are fully in scope of this project

- [ ] https://github.com/buerokratt/POC.CentOps/blob/main/docs/technical/api-spec.yml
- [ ] https://github.com/buerokratt/DMR.NET/blob/main/docs/design-architecture-for-dmr-related-services.doc.md

_**Informative**_

- [x] https://github.com/buerokratt/DMR.NET/blob/main/docs/technical-design-for-dmr-related-services.md
- [x] https://github.com/buerokratt/DMR.NET/blob/main/docs/technical/implementation.md
