### ISSUE TITLE
Software packaging

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#5]
AS A Bürokratt DevOps Engineer
I WANT TO have a standard pipeline for publishing market-ready software (updates)
SO THAT this could be done automatically and throughout different projects

### Acceptance Criteria

- [ ] GitHub is used as a version control environment
- [ ] Software packaging as a GitHub Actions pipeline
- [ ] New packages are created and published in GitHub Packages based on commit tags
- [ ] All packages are signed with a GPG key
