### ISSUE TITLE
Remote installation

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#7]
AS A Bürokratt DevOps Engineer
I WANT all Participants to have an automated process to install Bürokratt
SO THAT I shouldn't do it manually

AS A potential Bürokratt Client
I WANT TO start using Bürokratt whenever I'm ready for it
SO THAT I shouldn't plan any additional resources for it

### Acceptance Criteria

- [ ] Pre-installation test script to verify the correspondence of the environment
- [ ] Pre-installation script to install all necessary prerequisites to install Bürokratt
- [ ] Only software verified by Bürokratt can be installed
