### ISSUE TITLE
Messaging protocol for communication between Participants and Bürokratt

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#78]
AS AN Architect
I WANT TO have OpenAPI specification as a messaging protocol for communication between Participants and Bürokratt
SO THAT all the developments and integrations could be based on that

### Acceptance Criteria

- [ ] Messages sent and received are content-agnostic and must follow identical protocol
- [ ] Content of the message must be encrypted, so that only the participants with the appropriate key can read them
- [ ] Message type (`update manifest`, `chat message`, etc.) is defined
- [ ] Communication settings should be fetched from the manifest before sending and receiving the message

#### Encryption

- [ ] Allowed message encryption types must be configurable
- [ ] The message contains the encryption type used to encrypt the actual message container
- [ ] The scope of this issue is to cover AES, RSA, Triple DES, and Base64 (Base64 for insecure testing purposes), covering the functionalities by #114 and #115

#### Functionalities

- [ ] Covers all sections of **Acceptance Critera -> Functionalities** of #11
