### ISSUE TITLE
Institutions management

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/CentOps#84]
AS Bürokratt
I WANT TO to have a tool for Institutions management
SO THAT I could mange all Institutions in contract with Bürokratt via a GUI-based tool

### Acceptance Criteria

- [ ] Get a public list of all Institutions
- [ ] Get a private list of all Institutions
- [ ] Add new Institutions
- [ ] Update contact, etc. information of existing Institutions
- [ ] Change the status of existing Institutions
- [ ] Delete existing Institutions
